file_format: "1"
id: cradias
name: Cradias/Sweep
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - cradias_left
  - cradias_right
